local modpath = minetest.get_modpath(minetest.get_current_modname())

dofile(modpath .. "/nodes/crafting_bench.lua")
dofile(modpath .. "/nodes/threshing_sledge.lua")
dofile(modpath .. "/nodes/hammering_log.lua")
dofile(modpath .. "/nodes/grinding_wheel.lua")
dofile(modpath .. "/nodes/weaving_frame.lua")
dofile(modpath .. "/nodes/mixing_bucket.lua")

dofile(modpath .. "/crafts/crafting_bench.lua")
dofile(modpath .. "/crafts/threshing_sledge.lua")
dofile(modpath .. "/crafts/hammering_log.lua")
dofile(modpath .. "/crafts/grinding_wheel.lua")
dofile(modpath .. "/crafts/weaving_frame.lua")
dofile(modpath .. "/crafts/mixing_bucket.lua")
