name = exile_crafting_tables
description = Advanced crafting stations extracted from deprecated branch (weaving frame, hammering block, pottery wheel, wattle workstation).
depends = tech
author = Ozcodex
