name = exile_crafting_tables
description = Optional aesthetic workbenches for existing Exile craft types.
depends = tech, crafting, nodes_nature
supported_games = exile
author = Ozcodex

license = Unlicense
